require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'tmp/**/*'
    - 'examples/**'
    - Gemfile
    - Rakefile
    - '*.gemspec'
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100
  IgnoreCopDirectives: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AndOr:
  EnforcedStyle: conditionals

Style/SignalException:
  EnforcedStyle: semantic

Style/BlockDelimiters:
  EnforcedStyle: semantic